[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Compilation
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 100

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
